package com.data_management;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Stream;

/**
 * Implementation of {@link DataReader} that reads patient data from files
 * generated by the {@code FileOutputStrategy}.
 *
 * Each file in the specified directory contains records in this format:
 * {@code Patient ID: <id>, Timestamp: <timestamp>, Label: <label>, Data: <value>}
 *
 * All files in the directory are read and parsed into {@link PatientRecord}
 * objects, which are then stored in {@link DataStorage}.
 */
public class FileDataReader implements DataReader {

    // The directory path from which patient data files are read.
    private final String directoryPath;

    /**
     * Constructs a {@code FileDataReader} for the given directory.
     *
     * @param directoryPath the path to the directory containing patient data files,
     * must not be null or empty.
     */
    public FileDataReader(String directoryPath) {
        this.directoryPath = directoryPath;
    }

    /**
     * Reads all patient data files from the specified directory and stores
     * the parsed records in the given {@link DataStorage}.
     *
     * Each file is read line by line. Lines that do not match the expected
     * format are skipped and a warning is printed.
     *
     * @param dataStorage the storage where parsed patient data will be stored,
     * must not be null
     * @throws IOException if the directory cannot be read or does not exist
     */
    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        Path dirPath = Paths.get(directoryPath);

        if (!Files.exists(dirPath) || !Files.isDirectory(dirPath)) {
            throw new IOException("Directory not found: " + directoryPath);
        }

        // iterate over all files in the directory
        try (Stream<Path> files = Files.list(dirPath)) {
            files.filter(Files::isRegularFile)
                 .forEach(file -> {
                     try {
                         readFile(file, dataStorage);
                     } catch (IOException e) {
                         System.err.println("Error reading file: " + file + ": " + e.getMessage());
                     }
                 });
        }
    }

    /**
     * Reads and parses a single file, storing valid records in {@link DataStorage}.
     *
     * @param filePath the path to the file to read
     * @param dataStorage where parsed records will be stored
     * @throws IOException if the file cannot be read
     */
    private void readFile(Path filePath, DataStorage dataStorage) throws IOException {
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath.toFile()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                parseLine(line, dataStorage);
            }
        }
    }

    /**
     * Parses a single line of patient data and adds it to {@link DataStorage}.
     *
     * Expected format:
     * {@code Patient ID: 1, Timestamp: 1714376789050, Label: HeartRate, Data: 75.0}
     * Lines that do not match this format are skipped.
     *
     * @param line the line of text to parse
     * @param dataStorage where the parsed record will be added
     */
    private void parseLine(String line, DataStorage dataStorage) {
        try {
            // split on ", " to get each field
            String[] parts = line.split(", ");
            if (parts.length != 4) {
                System.err.println("Skipping malformed line: " + line);
                return;
            }

            int patientId = Integer.parseInt(parts[0].split(": ")[1].trim());
            long timestamp = Long.parseLong(parts[1].split(": ")[1].trim());
            String label = parts[2].split(": ")[1].trim();
            double value = Double.parseDouble(parts[3].split(": ")[1].trim().replace("%", ""));

            dataStorage.addPatientData(patientId, value, label, timestamp);

        } catch (Exception e) {
            System.err.println("Skipping malformed line: " + line);
        }
    }
}
